name: 01 - Default Workflow

on:
  pull_request:
          

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Commands
        run: |
          echo "Hello World"
          echo "You can run any command in your workflow that way with Github Actions"
