name: 02 - Secret Workflow

on:
  schedule:
  - cron: "0 1 * * *" # Runs at 01:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Commands with Secret
        env:
            SECRET_VALUE: ${{ secrets.SECRET_VALUE }}
        run: |
          echo "Hello World"
          echo "This is a secret value: $SECRET_VALUE"
          
      - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'GuillaumeFalourd'
          repository: 'formulas-training'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -l
          echo "CLONED REPO"
          cd formulas-training
          ls -l
