name: 12 - Run Workflow

on:
  workflow_run:
    workflows: ["Workflow Tester"]
    types: [completed] #requested

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"