name: 12 - Run Workflow

on:
  workflow_run:
    workflows: ["24 - Github Context"]
    types: 
      - completed 
      - requested

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - run: echo "First workflow was a success"