name: 12 - Run Workflow

on:
  workflow_run:
    workflows: ["Workflow Tester"]
    types: completed

jobs:
   get-pr-info:
    name: "Get information about the source run"
    runs-on: ubuntu-latest
    outputs:
      pullRequestNumber: ${{ steps.source-run-info.outputs.pullRequestNumber }}
    steps:
      - name: "Get information about the origin 'CI' run"
        uses: potiuk/get-workflow-origin@v1_1
        id: source-run-info
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
      - run: echo ${steps.source-run-info.outputs.pullRequestNumber}
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "First workflow was a failure"
          echo "Let's dispatch another event for backup"
          curl -X POST https://api.github.com/repos/GuillaumeFalourd/poc-github-actions/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "Start Dispatch Event Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'