name: 34 - Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string

jobs:
  test:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Inputs username (workflow call)
        if: ${{ inputs.username }} != ''
        run: echo ${{ inputs.username }}

      - name: Inputs username (workflow dispatch)
        if: ${{ github.event.inputs.username }} != ''
        run: echo ${{ github.event.inputs.username }}

#      - uses: ./.github/actions/my-action@v1
#        with:
#          username: ${{ inputs.username }}
#          token: ${{ secrets.token }}