name: 34 - Workflow call

on:
  push:

jobs:
  call-workflow-commit-hash:
    uses: tanimaroy2012/poc-github-actions/.github/workflows/33-reusable-workflow.yml@ba6294c776b98a3b4f28e8a0b804b71e4b8d0b48
    with:
      username: tanimaroy2012
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call-workflow-branch-ref:
    uses: tanimaroy2012/poc-github-actions/.github/workflows/33-reusable-workflow.yml@main
    with:
      username: tanimaroy2012
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call-workflow-tag:
    uses: tanimaroy2012/poc-github-actions/.github/workflows/33-reusable-workflow.yml@1.1.0
    with:
      username: tanimaroy2012
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}