name: Test 8

on:
  workflow_dispatch:
  release:
    types: [published]
    # tags:
    #   - 'prod-*'
    #   - 'dev-*'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.get_tag_version.outputs.version }}
    steps:
      - name: Get the version
        id: get_tag_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    if: contains( needs.job1.outputs.tag_version , 'dev-')
    steps:
      - run: echo "${{needs.job1.outputs.tag_version}}"

  job3:
    runs-on: ubuntu-latest
    needs: [job1]
    if: contains( needs.job1.outputs.tag_version , 'prod-')
    steps:
      - run: echo "${{needs.job1.outputs.tag_version}}"
