name: Test 5

env:
  REPORT_PATH: '**/report.txt'
  README_PATH: '**/README.md'
  WORKFLOW_PATH: '**/workflow-tester5.yml'

on:
  push:
    paths:
      - $REPORT_PATH
      - $README_PATH
      - $WORKFLOW_PATH
  pull_request:
    paths:
      - $REPORT_PATH
      - $README_PATH
      - $WORKFLOW_PATH
  workflow_dispatch:

jobs:
  test5:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $REPORT_PATH
          echo $README_PATH
          echo $WORKFLOW_PATH
      - run: |
          echo ${{ env.REPORT_PATH }}
          echo ${{ env.README_PATH }}
          echo ${{ env.WORKFLOW_PATH }}
